local BraindanceProtocol = {
rootPath =	"plugins.cyber_engine_tweaks.mods.braindance_protocol."
}

local BD = require(BraindanceProtocol.rootPath.."BD")

local Protocols = {
  Parents = {
	{ id = "Cheats"		, name = "Cheats"                       },
	{ id = "Crafting"	, name = "Crafting Recipes"             },
	{ id = "Cyberware"	, name = "Cyberware Items"              },
	{ id = "Facts"		, name = "Facts [Spoiler Alert!]"       },
	{ id = "ItemMods"	, name = "Item Modifications"			},
	{ id = "ItemSets"	, name = "Item Sets"                    },
	{ id = "Saves"		, name = "Saves"                        },
	{ id = "Teleport"	, name = "Teleport - V's Homes"         },
	{ id = "Teleport2"	, name = "Teleport - Generic"           },
	{ id = "Teleport3"	, name = "Teleport - NPCs"              },
	{ id = "Teleport4"	, name = "Teleport - Stores"            },
	{ id = "Teleport5"	, name = "Teleport - Ripperdocs"        },
	{ id = "Teleport6"	, name = "Teleport - Bonus Locations"   },
	{ id = "Time"		, name = "Time Options"					},
	{ id = "Utilities"	, name = "Utilities"                    },
	{ id = "Vehicles"	, name = "Vehicles"                     }
  },
  Items = {
-- Button:
--  	{ id = "ID", name "Display name" , parent = "Parent" , description = "Tooltip text" , type = "Button" , button_label = "button label" , cmd = function () print("Command to run") end },
-- Input:
--  	{ id = "ID" , name = "Display name" , parent = "Parent" , description = "Tooltip text" , type = "Input" , button_label = "button label" , value = number (default value) , cmd = function(value) print("Command to run") end },
-- Toggle:
--  	{ id = "ID" , name = "Display name" , parent = "Parent" , description = "Tooltip text" , type = "Toggle" , button_label1 = "off button label" , button_label2 = "on button label" , cmd = function(value) print("Command to run") end },
-- Select:
--  	{ id = "ID" , name = "Display name" , parent = "Parent" , description = "Tooltip text" , type = "Select" , options = "Option1\0Option2\0Option3\0" , cmd = function(value) print("Command to run") end },

-- Cheats
	{ id = "Platform.UnlockAllAchievements" , name = "Unlock All Achievements" , parent = "Cheats" , description = "Unlock all achievements on your platform (Steam / GoG)." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Platform.UnlockAllAchievements() end },
	{ id = "Player.MaxOut" , name = "MaxOut Level, Attributes, etc" , parent = "Cheats" , description = "Max Level, Attributes, Skill Points, Money." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Player.MaxOut() end },
	{ id = "Player.Respec" , name = "Respec perks and attributes" , parent = "Cheats" , description = "Respec attributes and perks." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Player.Respec() end },
	{ id = "Player.GodMode" , name = "GodMode" , parent = "Cheats" , description = "Gives you pseudo \"god mode\". Permanent to your SaveFile." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Player.GodMode() end },
	{ id = "Player.AddMoney" , name = "Add Money" , parent = "Cheats" , description = "Gives the player specified amount of money." , type = "Input" , button_label = "Add" , value = 10000 , cmd = function(value) BD.Cheats.Player.AddMoney(value) end },
	{ id = "Johnny.AddItems" , name = "Add Johnny's Items" , parent = "Cheats" , description = "Adds Johnny's Legendary Items and his Porsche." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Johnny.AddItems() end },
	
-- Crafting
	{ id = "Crafting.AddAll" , name = "Add All Recipes & Materials" , parent = "Crafting" , description = "Add all Recipes & Materials." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Crafting.AddAll() end },
	{ id = "Crafting.AddLegendaryMaterials" , name = "Add Legendary Materials" , parent = "Crafting" , description = "Add specified amount of legendary crafting materials." , type = "Input" , button_label = "Add" , value = 50 , cmd = function(value) BD.Cheats.Crafting.AddLegendaryMaterials(value) end },
	{ id = "Crafting.AddLegendaryRecipes" , name = "Add Legendary Recipes" , parent = "Crafting" , description = "Adds all legendary crafting recipes." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Crafting.AddLegendaryRecipes() end },
	{ id = "Crafting.AddEpicRecipes" , name = "Add Epic Recipes" , parent = "Crafting" , description = "Adds all epic crafting recipes." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Crafting.AddEpicRecipes() end },
	{ id = "Crafting.AddRareRecipes" , name = "Add Rare Recipes" , parent = "Crafting" , description = "Adds all rare crafting recipes." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Crafting.AddRareRecipes() end },
	{ id = "Crafting.AddUncommonRecipes" , name = "Add Uncommon Recipes" , parent = "Crafting" , description = "Adds all uncommon crafting recipes." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Crafting.AddUncommonRecipes() end },
	{ id = "Crafting.AddCommonRecipes" , name = "Add Common Recipes" , parent = "Crafting" , description = "Adds all common crafting recipes." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Crafting.AddCommonRecipes() end },
	{ id = "Crafting.AddModRecipes" , name = "Add Mod Recipes" , parent = "Crafting" , description = "Adds all mod recipes (clothing + cyberware + weapon mods)." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Crafting.AddModRecipes() end },
	{ id = "Crafting.AddMedRecipes" , name = "Add Medicine Recipes" , parent = "Crafting" , description = "Adds all medicine recipes." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Crafting.AddMedRecipes() end },
	{ id = "Crafting.AddGrenadeRecipes" , name = "Add Grenade Recipes" , parent = "Crafting" , description = "Adds all grenade recipes." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Crafting.AddGrenadeRecipes() end },

-- Cyberware
	{ id = "Cyberware.AddAllCW" , name = "Add All Cyberware" , parent = "Cyberware" , description = "Adds all Cyberware items (all qualities)." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Cyberware.AddAllCW() end },
	{ id = "Cyberware.AddIconicCW" , name = "Add Iconic Cyberware" , parent = "Cyberware" , description = "Adds all iconic Cyberware items." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Cyberware.AddIconicCW() end },
	{ id = "Cyberware.AddLegendaryCW" , name = "Add Legendary Cyberware" , parent = "Cyberware" , description = "Adds all legendary Cyberware items." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Cyberware.AddLegendaryCW() end },
	{ id = "Cyberware.AddEpicCW" , name = "Add Epic Cyberware" , parent = "Cyberware" , description = "Adds all epic Cyberware items." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Cyberware.AddEpicCW() end },
	{ id = "Cyberware.AddRareCW" , name = "Add Rare Cyberware" , parent = "Cyberware" , description = "Adds all rare Cyberware items." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Cyberware.AddRareCW() end },
	{ id = "Cyberware.AddUncommonCW" , name = "Add Uncommon Cyberware" , parent = "Cyberware" , description = "Adds all uncommon Cyberware items." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Cyberware.AddUncommonCW() end },
	{ id = "Cyberware.AddCommonCW" , name = "Add Common Cyberware" , parent = "Cyberware" , description = "Adds all common Cyberware items." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Cyberware.AddCommonCW() end },

-- Facts
	{ id = "Facts.SkippyMode" , name = "Set Skippy's Mode" , parent = "Facts" , description = "Sets Skippy to \"Stone Cold Killer\" mode or \"Puppy-Loving Pacifist\" mode." , type = "Toggle" , button_label1 = "Killer" , button_label2 = "Pacifist" , cmd = function(value) if value then BD.Cheats.Facts.SetSkippyToPLP() else BD.Cheats.Facts.SetSkippyToSCK() end end },
	{ id = "Facts.SkippyAttitude" , name = "Set Skippy's Attitude" , parent = "Facts" , description = "Sets Skippy to being \"Friendly\" or \"Angry\"." , type = "Toggle" , button_label1 = "Angry" , button_label2 = "Friendly" , cmd = function(value) if value then BD.Cheats.Facts.SetSkippyToFriendly() else BD.Cheats.Facts.SetSkippyToHostile() end end },
	{ id = "Facts.JackieBody" , name = "Set Jackie's Fate" , parent = "Facts" , description = "Select where you sent Jackie's body." , type = "Select" , options = "Send to victor\0Send to Welles\0Left in the Car\0" , cmd = function(value) if value == 0 then BD.Cheats.Facts.SendJackieToViktor() elseif value == 1 then BD.Cheats.Facts.SendJackieToWelles() elseif value == 2 then BD.Cheats.Facts.LeftJackieInCar() end end },
	{ id = "Facts.GoroFate" , name = "Set Goro's Fate" , parent = "Facts" , description = "Set Takemura to alive (you saved him) or dead (you left him to die)." , type = "Toggle" , button_label1 = "Dead" , button_label2 = "Alive" , cmd = function(value) if value then BD.Cheats.Facts.SetGoroAlive() else BD.Cheats.Facts.SetGoroDead() end end },
	{ id = "Facts.SetFingersToFriendly" , name = "Set Fingers To Friendly" , parent = "Facts" , description = "Fingers M.D. is now friendly." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Facts.SetFingersToFriendly() end },
	{ id = "Facts.SetJudyRomance" , name = "Set Judy Romance" , parent = "Facts" , description = "Judy is now romanceable." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Facts.SetJudyRomance() end },
	-- 	{ id = "Facts.SetRiverRomance" , name = "Set River Romance" , parent = "Facts" , description = "River is now romanceable." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Facts.SetRiverRomance() end },
	-- 	{ id = "Facts.SetPanamRomance" , name = "Set Panam Romance" , parent = "Facts" , description = "Panam is now romanceable." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Facts.SetPanamRomance() end },
	{ id = "Facts.SetKerryRomance" , name = "Set Kerry Romance" , parent = "Facts" , description = "Kerry is now romanceable." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Facts.SetKerryRomance() end },
	{ id = "Facts.SetJohnnyAsFriend" , name = "Set Johnny As Friend" , parent = "Facts" , description = "Unlock Johnny's secret ending." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Facts.SetJohnnyAsFriend() end },

-- ItemSets
	{ id = "ItemSets.AddAllSets" , name = "Add All Item Sets" , parent = "ItemSets" , description = "Adds All Item Sets Listed Below." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddAllSets() end },
	{ id = "ItemSets.AddSetCorpo" , name = "Add Corpo Set" , parent = "ItemSets" , description = "Adds the \"Corpo\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetCorpo() end },
	{ id = "ItemSets.AddSetFixer" , name = "Add Fixer Set" , parent = "ItemSets" , description = "Adds the \"Fixer\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetFixer() end },
	{ id = "ItemSets.AddSetMaxTac" , name = "Add MaxTac Set" , parent = "ItemSets" , description = "Adds the \"MaxTac\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetMaxTac() end },
	{ id = "ItemSets.AddSetMedia" , name = "Add Media Set" , parent = "ItemSets" , description = "Adds the \"Media\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetMedia() end },
	{ id = "ItemSets.AddSetNetrunner" , name = "Add Netrunner Set" , parent = "ItemSets" , description = "Adds the \"Netrunner\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetNetrunner() end },
	{ id = "ItemSets.AddSetNomad" , name = "Add Nomad Set" , parent = "ItemSets" , description = "Adds the \"Nomad\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetNomad() end },
	{ id = "ItemSets.AddSetPolice" , name = "Add Police Set" , parent = "ItemSets" , description = "Adds the \"Police\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetPolice() end },
	{ id = "ItemSets.AddSetRocker" , name = "Add Rocker Set" , parent = "ItemSets" , description = "Adds the \"Rocker\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetRocker() end },
	{ id = "ItemSets.AddSetSolo" , name = "Add Solo Set" , parent = "ItemSets" , description = "Adds the \"Solo\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetSolo() end },
	{ id = "ItemSets.AddSetTechie" , name = "Add Techie Set" , parent = "ItemSets" , description = "Adds the \"Techie\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetTechie() end },
	{ id = "ItemSets.AddSetVCorpo" , name = "Add V's Corpo Set" , parent = "ItemSets" , description = "Adds \"V's Corpo\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetVCorpo() end },
	{ id = "ItemSets.AddSetVNomad" , name = "Add V's Nomad Set" , parent = "ItemSets" , description = "Adds \"V's Nomad\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetVNomad() end },
	{ id = "ItemSets.AddSetVStreetkid" , name = "Add V's Streetkid Set" , parent = "ItemSets" , description = "Adds \"V's Streetkid\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetVStreetkid() end },
	{ id = "ItemSets.AddSetVEpilogue" , name = "Add V's Epilogue Set" , parent = "ItemSets" , description = "Adds \"V's Epilogue\" item set." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetVEpilogue() end },
	{ id = "ItemSets.AddSetVMisc" , name = "Add V's Misc Set" , parent = "ItemSets" , description = "Adds \"the rest\" of V's default gear." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.ItemSets.AddSetVMisc() end },

-- Items
	{ id = "Legend.UpgradeAll" , name = "Legendize All Equipped Items" , parent = "ItemMods" , description = "Makes all equipped items legendary with max stats (except mods)" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Legend.UpgradeAll() end },
	{ id = "Legend.UpgradeWeapons" , name = "Legendize Equipped Weapons" , parent = "ItemMods" , description = "Makes all equipped weapons legendary with max stats" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Legend.UpgradeWeapons() end },
	{ id = "Legend.UpgradeArmor" , name = "Legendize Equipped Armor" , parent = "ItemMods" , description = "Makes all equipped armor legendary with max stats" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Legend.UpgradeArmor() end },
	{ id = "Legend.UpgradeMods" , name = "Legendize Non-Equipped Mods" , parent = "ItemMods" , description = "Makes all non-equppied mods legendary with max stats" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Legend.UpgradeMods() end },
	{ id = "Legend.UpgradeCW" , name = "Legendize Equipped Cyberware" , parent = "ItemMods" , description = "Makes all Cyberware legendary. NOTE: This is just for aesthetics.\nYou should add the real items, from the other commands" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Legend.UpgradeCW() end },
	

-- Teleportation
	-- Player Homes
	{ id = "Teleport.VsApartment" , name = "V's Apartment" , parent = "Teleport" , description = "Teleport to V's Apartment." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.VsApartment() end },
	{ id = "Teleport.VsMansion" , name = "V's Mansion" , parent = "Teleport" , description = "Teleport to V's Mansion." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.VsMansion() end },
	-- Generic Locations
	{ id = "Teleport.GenericAfterlife" , name = "Afterlife" , parent = "Teleport2" , description = "Teleport to The Afterlife" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericAfterlife() end },
	{ id = "Teleport.GenericClouds" , name = "Clouds" , parent = "Teleport2" , description = "Teleport to Clouds" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericClouds() end },
	{ id = "Teleport.GenericLizziesBar" , name = "Lizzie's Bar" , parent = "Teleport2" , description = "Teleport to Lizzie's Bar" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericLizziesBar() end },
	{ id = "Teleport.GenericTotentanzClub" , name = "Totentanz Club" , parent = "Teleport2" , description = "Teleport to Totentanz Club" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericTotentanzClub() end },
	{ id = "Teleport.GenericDMCInside" , name = "Dark Matter Club (inside)" , parent = "Teleport2" , description = "Teleport to Dark Matter Club (inside)" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericDMCInside() end },
	{ id = "Teleport.GenericDMCOutside" , name = "Dark Matter Club (outside)" , parent = "Teleport2" , description = "Teleport to Dark Matter Club (outside)" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericDMCOutside() end },
	{ id = "Teleport.GenericElCoyoteCojo" , name = "El Coyote Cojo" , parent = "Teleport2" , description = "Teleport to El Coyote Cojo" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericElCoyoteCojo() end },
	{ id = "Teleport.GenericNoTellMotel" , name = "No-Tell Motel" , parent = "Teleport2" , description = "Teleport to No-Tell Motel" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericNoTellMotel() end },
	{ id = "Teleport.GenericSunsetMotel" , name = "Sunset Motel" , parent = "Teleport2" , description = "Teleport to Sunset Motel" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericSunsetMotel() end },
	{ id = "Teleport.GenericSunshineMotel" , name = "Sunshine Motel" , parent = "Teleport2" , description = "Teleport to Sunshine Motel" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericSunshineMotel() end },
	{ id = "Teleport.GenericMobileCamp" , name = "Mobile Camp" , parent = "Teleport2" , description = "Teleport to Mobile Camp" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericMobileCamp() end },
	{ id = "Teleport.GenericNomadCamp" , name = "Nomad Camp" , parent = "Teleport2" , description = "Teleport to Nomad Camp" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericNomadCamp() end },
	{ id = "Teleport.GenericJigJigStreet" , name = "Jig Jig Street" , parent = "Teleport2" , description = "Teleport to Jig Jig Street" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericJigJigStreet() end },
	{ id = "Teleport.GenericPacificaDistrict" , name = "Pacifica Disctrict" , parent = "Teleport2" , description = "Teleport to Pacifica District" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericPacificaDistrict() end },
	{ id = "Teleport.GenericGrandImperialMall" , name = "Grand Imperial Mall" , parent = "Teleport2" , description = "Teleport to Grand Imperial Mall" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericGrandImperialMall() end },
	{ id = "Teleport.GenericDelamainHQ" , name = "Delamain HQ" , parent = "Teleport2" , description = "Teleport to Delamain HQ" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericDelamainHQ() end },
	{ id = "Teleport.GenericReconciliationPark" , name = "Reconciliation Park" , parent = "Teleport2" , description = "Teleport to Reconciliation Park" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericReconciliationPark() end },
	{ id = "Teleport.GenericRockyRidge" , name = "Rocky Ridge" , parent = "Teleport2" , description = "Teleport to Rokcy Ridge" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.GenericRockyRidge() end },
	-- NPC Locations
	{ id = "Teleport.NPCJudyHouse" , name = "Judy" , parent = "Teleport3" , description = "Teleport to Judy's Apartment" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCJudyHouse() end },
	{ id = "Teleport.NPCRiverHouse" , name = "River" , parent = "Teleport3" , description = "Teleport to River's House" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCRiverHouse() end },
	{ id = "Teleport.NPCMisty" , name = "Misty" , parent = "Teleport3" , description = "Teleport to Misty's Esoterica" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCMisty() end },
	{ id = "Teleport.NPCClaireGarage" , name = "Claire" , parent = "Teleport3" , description = "Teleport to Claire's Garage" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCClaireGarage() end },
	{ id = "Teleport.NPCDakotaSmith" , name = "Dakota Smith" , parent = "Teleport3" , description = "Teleport to Dakota Smith" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCDakotaSmith() end },
	{ id = "Teleport.NPCDinoDinovic" , name = "Dino Dinovic" , parent = "Teleport3" , description = "Teleport to Dino Dinovic" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCDinoDinovic() end },
	{ id = "Teleport.NPCReyes" , name = "Mumar Reyes" , parent = "Teleport3" , description = "Teleport to Mumar 'El Caliptan' Reyes" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCReyes() end },
	{ id = "Teleport.NPCPadre" , name = "Padre" , parent = "Teleport3" , description = "Teleport to Sebastian 'Padre' Ibarra" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCPadre() end },
	{ id = "Teleport.NPCReginaJones" , name = "Regina Jones" , parent = "Teleport3" , description = "Teleport to Regina Jones" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCReginaJones() end },
	{ id = "Teleport.NPCRogueAmendiares" , name = "Rogue" , parent = "Teleport3" , description = "Teleport to Rogue Amendiares" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCRogueAmendiares() end },
	{ id = "Teleport.NPCWakakoOkada" , name = "Wakako Okada" , parent = "Teleport3" , description = "Teleport to Wakako Okada" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCWakakoOkada() end },
	{ id = "Teleport.NPCDeadDexter" , name = "Dexter DeShawn (dead)" , parent = "Teleport3" , description = "Teleport to the corpse of Dexter DeShawn" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.NPCDeadDexter() end },
	-- Store Locations
	{ id = "Teleport.ShopClothing1" , name = "Clothing Shop #1" , parent = "Teleport4" , description = "Teleport to Pershing ST Store" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing1() end }, -- Clothing Stores
	{ id = "Teleport.ShopClothing2" , name = "Clothing Shop #2" , parent = "Teleport4" , description = "Teleport to Little China North Store" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing2() end },
	{ id = "Teleport.ShopClothing3" , name = "Clothing Shop #3" , parent = "Teleport4" , description = "Teleport to Kabuki Store" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing3() end },
	{ id = "Teleport.ShopClothing4" , name = "Clothing Shop #4" , parent = "Teleport4" , description = "Teleport to Blossoming Sakura Clothier" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing4() end },
	{ id = "Teleport.ShopClothing5" , name = "Clothing Shop #5" , parent = "Teleport4" , description = "Teleport to Lele Park Store" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing5() end },
	{ id = "Teleport.ShopClothing6" , name = "Clothing Shop #6" , parent = "Teleport4" , description = "Teleport to Red Peaks Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing6() end },
	{ id = "Teleport.ShopClothing7" , name = "Clothing Shop #7" , parent = "Teleport4" , description = "Teleport to Mallagra&Manzanita Store" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing7() end },
	{ id = "Teleport.ShopClothing8" , name = "Clothing Shop #8" , parent = "Teleport4" , description = "Teleport to Manufactory Market Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing8() end },
	{ id = "Teleport.ShopClothing9" , name = "Clothing Shop #9" , parent = "Teleport4" , description = "Teleport to West Wind Estate Store" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing9() end },
	{ id = "Teleport.ShopClothing10" , name = "Clothing Shop #10" , parent = "Teleport4" , description = "Teleport to Wellsprings Store" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing10() end },
	{ id = "Teleport.ShopClothing11" , name = "Clothing Shop #11" , parent = "Teleport4" , description = "Teleport to Appel De Paris" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing11() end },
	{ id = "Teleport.ShopClothing12" , name = "Clothing Shop #12" , parent = "Teleport4" , description = "Teleport to Jinguji" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopClothing12() end },
	{ id = "Teleport.ShopMelee1" , name = "Melee Shop #1" , parent = "Teleport4" , description = "Teleport to Coach Fred" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopMelee1() end }, -- Melee Weapon Shops
	{ id = "Teleport.ShopMelee2" , name = "Melee Shop #2" , parent = "Teleport4" , description = "Teleport to Crescent&Broad Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopMelee2() end },
	{ id = "Teleport.ShopMelee3" , name = "Melee Shop #3" , parent = "Teleport4" , description = "Teleport to West Wind Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopMelee3() end },
	{ id = "Teleport.ShopMelee4" , name = "Melee Shop #4" , parent = "Teleport4" , description = "Teleport to Rancho Coronado Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopMelee4() end },
	{ id = "Teleport.ShopMelee5" , name = "Melee Shop #5" , parent = "Teleport4" , description = "Teleport to Tango Tors Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopMelee5() end },
	{ id = "Teleport.ShopNetrunner1" , name = "Netrunner Shop #1" , parent = "Teleport4" , description = "Teleport to Yoko Tsuru" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopNetrunner1() end }, -- Netrunner Shops
	{ id = "Teleport.ShopNetrunner2" , name = "Netrunner Shop #2" , parent = "Teleport4" , description = "Teleport to Japantown Netrunner" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopNetrunner2() end },
	{ id = "Teleport.ShopNetrunner3" , name = "Netrunner Shop #3" , parent = "Teleport4" , description = "Teleport to Chang Hoon Nam" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopNetrunner3() end },
	{ id = "Teleport.ShopNetrunner4" , name = "Netrunner Shop #4" , parent = "Teleport4" , description = "Teleport to Costa View Netrunner" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopNetrunner4() end },
	{ id = "Teleport.ShopNetrunner5" , name = "Netrunner Shop #5" , parent = "Teleport4" , description = "Teleport to Vista del Rey Netrunner" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopNetrunner5() end },
	{ id = "Teleport.ShopWeapons1" , name = "Weapon Shop #1" , parent = "Teleport4" , description = "Teleport to Wilson Shop" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons1() end }, -- Weapon Shops
	{ id = "Teleport.ShopWeapons2" , name = "Weapon Shop #2" , parent = "Teleport4" , description = "Teleport to Straight Shooter" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons2() end },
	{ id = "Teleport.ShopWeapons3" , name = "Weapon Shop #3" , parent = "Teleport4" , description = "Teleport to Iron & Lead" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons3() end },
	{ id = "Teleport.ShopWeapons4" , name = "Weapon Shop #4" , parent = "Teleport4" , description = "Teleport to Maelstrom Heat" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons4() end },
	{ id = "Teleport.ShopWeapons5" , name = "Weapon Shop #5" , parent = "Teleport4" , description = "Teleport to Skyline&Salinas Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons5() end },
	{ id = "Teleport.ShopWeapons6" , name = "Weapon Shop #6" , parent = "Teleport4" , description = "Teleport to Halsey&MLK Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons6() end },
	{ id = "Teleport.ShopWeapons7" , name = "Weapon Shop #7" , parent = "Teleport4" , description = "Teleport to Cannery Plaza Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons7() end },
	{ id = "Teleport.ShopWeapons8" , name = "Weapon Shop #8" , parent = "Teleport4" , description = "Teleport to Ventura&Skyline Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons8() end },
	{ id = "Teleport.ShopWeapons9" , name = "Weapon Shop #9" , parent = "Teleport4" , description = "Teleport to College ST Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons9() end },
	{ id = "Teleport.ShopWeapons10" , name = "Weapon Shop #10" , parent = "Teleport4" , description = "Teleport to Sunset Motel Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons10() end },
	{ id = "Teleport.ShopWeapons11" , name = "Weapon Shop #11" , parent = "Teleport4" , description = "Teleport to Mobile Camp Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons11() end },
	{ id = "Teleport.ShopWeapons12" , name = "Weapon Shop #12" , parent = "Teleport4" , description = "Teleport to Nomad Camp Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons12() end },
	{ id = "Teleport.ShopWeapons13" , name = "Weapon Shop #13" , parent = "Teleport4" , description = "Teleport to Rancho Coronado East Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons13() end },
	{ id = "Teleport.ShopWeapons14" , name = "Weapon Shop #14" , parent = "Teleport4" , description = "Teleport to Manufactory Market Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons14() end },
	{ id = "Teleport.ShopWeapons15" , name = "Weapon Shop #15" , parent = "Teleport4" , description = "Teleport to Pacifica Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons15() end },
	{ id = "Teleport.ShopWeapons16" , name = "Weapon Shop #16" , parent = "Teleport4" , description = "Teleport to Fuel Station Vendor" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.ShopWeapons16() end },
	-- Ripperdoc Locations
	{ id = "Teleport.Ripperdoc1" , name = "Ripperdoc #1" , parent = "Teleport5" , description = "Teleport to Viktor's Clinic" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc1() end }, 
	{ id = "Teleport.Ripperdoc2" , name = "Ripperdoc #2" , parent = "Teleport5" , description = "Teleport to Cassius Ryder's Clinic" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc2() end },
	{ id = "Teleport.Ripperdoc3" , name = "Ripperdoc #3" , parent = "Teleport5" , description = "Teleport to Buck's Clinic" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc3() end },
	{ id = "Teleport.Ripperdoc4" , name = "Ripperdoc #4" , parent = "Teleport5" , description = "Teleport to Dr. Chrome" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc4() end },
	{ id = "Teleport.Ripperdoc5" , name = "Ripperdoc #5" , parent = "Teleport5" , description = "Teleport to Instant Implants" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc5() end },
	{ id = "Teleport.Ripperdoc6" , name = "Ripperdoc #6" , parent = "Teleport5" , description = "Teleport to Cherry Blossom Market Ripperdoc" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc6() end },
	{ id = "Teleport.Ripperdoc7" , name = "Ripperdoc #7" , parent = "Teleport5" , description = "Teleport to Fingers M.D." , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc7() end },
	{ id = "Teleport.Ripperdoc8" , name = "Ripperdoc #8" , parent = "Teleport5" , description = "Teleport to Skyline & Republic Ripperdoc" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc8() end },
	{ id = "Teleport.Ripperdoc9" , name = "Ripperdoc #9" , parent = "Teleport5" , description = "Teleport to Palms View Plaza Ripperdoc" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc9() end },
	{ id = "Teleport.Ripperdoc10" , name = "Ripperdoc #10" , parent = "Teleport5" , description = "Teleport to Kraviz's Clinic" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc10() end },
	{ id = "Teleport.Ripperdoc11" , name = "Ripperdoc #11" , parent = "Teleport5" , description = "Teleport to Wolleson ST Ripperdoc" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc11() end },
	{ id = "Teleport.Ripperdoc12" , name = "Ripperdoc #12" , parent = "Teleport5" , description = "Teleport to West Wind Ripperdoc" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc12() end },
	{ id = "Teleport.Ripperdoc13" , name = "Ripperdoc #13" , parent = "Teleport5" , description = "Teleport to Octavio's Clinic" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc13() end },
	{ id = "Teleport.Ripperdoc14" , name = "Ripperdoc #14" , parent = "Teleport5" , description = "Teleport to Mobile Camp Ripperdoc" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc14() end },
	{ id = "Teleport.Ripperdoc15" , name = "Ripperdoc #15" , parent = "Teleport5" , description = "Teleport to Nomad Camp Ripperdoc" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.Ripperdoc15() end },
	-- Extra/Bonus/Out-of-bounds Locations
	{ id = "Teleport.BonusAkulovPenthouse" , name = "Akulov Penthouse" , parent = "Teleport6" , description = "Teleport to Akulov Penthouse" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusAkulovPenthouse() end },
	{ id = "Teleport.BonusArasakaOrbitalStation" , name = "Arasaka Orbital Station" , parent = "Teleport6" , description = "Teleport to Arasaka Orbital Station" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusArasakaOrbitalStation() end },
	{ id = "Teleport.BonusArasakaTowerJungle" , name = "Arasaka Tower Jungle" , parent = "Teleport6" , description = "Teleport to Arasaka Tower Jungle" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusArasakaTowerJungle() end },
	{ id = "Teleport.BonusArasakaTowerTemple" , name = "Arasaka Tower Temple" , parent = "Teleport6" , description = "Teleport to Arasaka Tower Temple" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusArasakaTowerTemple() end },
	{ id = "Teleport.BonusBadlandsTunnelEntrance" , name = "Badlands Tunnel Entrance" , parent = "Teleport6" , description = "Teleport to Badlands Tunnel Entrance" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusBadlandsTunnelEntrance() end },
	{ id = "Teleport.BonusCloudsInside" , name = "Clouds (inside)" , parent = "Teleport6" , description = "Teleport to the inside of Clouds" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusCloudsInside() end },
	{ id = "Teleport.BonusJohnnyInterrogationRoom" , name = "Johnny Interrogation Room" , parent = "Teleport6" , description = "Teleport to Johnny's Interrogation Room" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusJohnnyInterrogationRoom() end },
	{ id = "Teleport.BonusKonpekiPlazaHotelSuite" , name = "Konpeki Plaza Suite" , parent = "Teleport6" , description = "Teleport to the hotel suite in Konpeki Plaza" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusKonpekiPlazaHotelSuite() end },
	{ id = "Teleport.BonusKonpekiPlazaYorinobuRoom" , name = "Konpeki Plaza Yorinobu's Room" , parent = "Teleport6" , description = "Teleport to Yorinobu's room in Konpeki Plaza" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusKonpekiPlazaYorinobuRoom() end },
	{ id = "Teleport.BonusBlackwallTunnel" , name = "Blackwall Tunnel" , parent = "Teleport6" , description = "Teleport to Blackwall Tunnel" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusBlackwallTunnel() end },
	{ id = "Teleport.BonusNCPDRoom" , name = "NCPD Room" , parent = "Teleport6" , description = "Teleport to NCPD Room" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusNCPDRoom() end },
	{ id = "Teleport.BonusMegaH8Top" , name = "Megabuilding H8 Top" , parent = "Teleport6" , description = "Teleport to the top of Megabuilding H8" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusMegaH8Top() end },
	{ id = "Teleport.BonusMegaH10Top" , name = "Megabuilding H10 Top" , parent = "Teleport6" , description = "Teleport to the top of Megabuilding H10" , type = "Button" , button_label = "Execute" , cmd = function() BD.Cheats.Teleport.BonusMegaH10Top() end },

-- Time Options
	{ id = "Time.SetTime" , name = "Set Time" , parent = "Time" , description = "Set the time - Use 24h format" , type = "Input" , button_label = "Set" , value = 18 , cmd = function(value) BD.Time.SetTime(value) end },
	{ id = "Time.SetTimeTo06AM" , name = "6AM / 06:00" , parent = "Time" , description = "Sets the time to 6AM / 06:00" , type = "Button" , button_label = "Execute" , cmd = function() BD.Time.SetTimeTo06AM() end },
	{ id = "Time.SetTimeTo10PM" , name = "10PM / 22:00" , parent = "Time" , description = "Sets the time to 10PM / 22:00" , type = "Button" , button_label = "Execute" , cmd = function() BD.Time.SetTimeTo10PM() end },
	
-- Save File Editing	
	{ id = "Saves.DisableAutosave" , name = "Disable Autosave" , parent = "Saves" , description = "Disables auto saving." , type = "Button" , button_label = "Execute" , cmd = function() BD.Saves.DisableAutosave() end },
	{ id = "Saves.DecreaseAutosaves" , name = "Decrease Autosaves" , parent = "Saves" , description = "Decreases time between auto saves." , type = "Button" , button_label = "Execute" , cmd = function() BD.Saves.DecreaseAutosaves() end },
	{ id = "Saves.IncreaseAutosaves" , name = "Increase Autosaves" , parent = "Saves" , description = "Increases time between auto saves." , type = "Button" , button_label = "Execute" , cmd = function() BD.Saves.IncreaseAutosaves() end },
	{ id = "Saves.IncreaseQuicksaves" , name = "Increase Quicksaves" , parent = "Saves" , description = "Increase Quicksave slots to 10." , type = "Button" , button_label = "Execute" , cmd = function() BD.Saves.IncreaseQuicksaves() end },

-- Utilities / Shopper
	{ id = "Shopper.SellJunk" , name = "Sell Junk" , parent = "Utilities" , description = "\"Sells\" all common junk items from players inventory by removing\nthem and adding appropriate amount of Eddies back." , type = "Button" , button_label = "Execute" , cmd = function() BD.Shopper.SellJunk() end },
	{ id = "Shopper.SellAlcohol" , name = "Sell Alcohol" , parent = "Utilities" , description = "As above but for alcohol (consumables)." , type = "Button" , button_label = "Execute" , cmd = function() BD.Shopper.SellAlcohol() end },
	{ id = "Shopper.SellJewellery" , name = "Sell Jewellery" , parent = "Utilities" , description = "As above but for jewellery (pricier junk)." , type = "Button" , button_label = "Execute" , cmd = function() BD.Shopper.SellJewellery() end },
	{ id = "Shopper.SellAllUselessItems" , name = "Sell All Useless Items" , parent = "Utilities" , description = "As above but all at the same time." , type = "Button" , button_label = "Execute" , cmd = function() BD.Shopper.SellAllUselessItems() end },

-- Vehicles
	{ id = "Vehicles.GetAll" , name = "Get All Vehicles" , parent = "Vehicles" , description = "Grants you all ownable player vehicles." , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetAll() end },
	{ id = "Vehicles.PreventKnockdown", name = "Prevent Vehicle Knock Down" , parent = "Vehicles" , description = "Prevent getting knocked down by vehicles" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.PreventKnockdown() end },
	-- Individual Vehicles
	{ id = "Vehicles.GetMahirSupronFS3", name = "Mahir - Supron FS3" , parent = "Vehicles" , description = "Add the vehicle Mahir - Supron FS3" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetMahirSupronFS3() end },
	{ id = "Vehicles.GetMaiMaiP126", name = "Makigai - MaiMai P126" , parent = "Vehicles" , description = "Add the vehicle Makigai - MaiMai P126" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetMaiMaiP126() end },
	{ id = "Vehicles.GetThortonColbyC125", name = "Thorton - Colby C125" , parent = "Vehicles" , description = "Add the vehicle Thorton - Colby C125" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetThortonColbyC125() end },
	{ id = "Vehicles.GetThortonColbyCX410Green", name = "Thorton - Colby CX 410 Butte (green)" , parent = "Vehicles" , description = "Add the vehicle Thorton - Colby CX 410 Butte (green)" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetThortonColbyCX410Green() end },
	{ id = "Vehicles.GetThortonColbyCX410Red", name = "Thorton - Colby CX 410 Butte (red)" , parent = "Vehicles" , description = "Add the vehicle Thorton - Colby CX 410 Butte (red)" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetThortonColbyCX410Red() end },
	{ id = "Vehicles.GetThortonColbyLittleMule", name = "Thorton - Colby 'Little Mule'" , parent = "Vehicles" , description = "Add the vehicle Thorton - Colby 'Little Mule'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetThortonColbyLittleMule() end },
	{ id = "Vehicles.GetThortonGalenaG240", name = "Thorton - Galena G240" , parent = "Vehicles" , description = "Add the vehicle Thorton - Galena G240" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetThortonGalenaG240() end },
	{ id = "Vehicles.GetThortonGalenaGecko", name = "Thorton - Galena 'Gecko'" , parent = "Vehicles" , description = "Add the vehicle Thorton - Galena 'Gecko'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetThortonGalenaGecko() end },
	{ id = "Vehicles.GetThortonGalenaRattler", name = "Thorton - Galena 'Rattler'" , parent = "Vehicles" , description = "Add the vehicle Thorton - Galena 'Rattler'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetThortonGalenaRattler() end },
	{ id = "Vehicles.GetThortonMackinawMTL1", name = "Thorton - Mackinaw MTL1" , parent = "Vehicles" , description = "Add the vehicle Thorton - Mackinaw MTL1" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetThortonMackinawMTL1() end },
	{ id = "Vehicles.GetThortonMackinawBeast", name = "Thorton - Mackinaw 'Beast'" , parent = "Vehicles" , description = "Add the vehicle Thorton - Mackinaw 'Beast'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetThortonMackinawBeast() end },
	{ id = "Vehicles.GetVillefortAlvaradoVato", name = "Villefort - Alvarado 'Vato'" , parent = "Vehicles" , description = "Add the vehicle Villefort - Alvarado 'Vato'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetVillefortAlvaradoVato() end },
	{ id = "Vehicles.GetVillefortAlvaradoV4F570Delegate", name = "Villefort - Alvarado V4F 570 Delegate" , parent = "Vehicles" , description = "Add the vehicle Villefort - Alvarado V4F 570 Delegate" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetVillefortAlvaradoV4F570Delegate() end },
	{ id = "Vehicles.GetVillefortColumbusV340FFreight", name = "Villefort - Columbus V340-F Freight" , parent = "Vehicles" , description = "Add the vehicle Villefort - Columbus V340-F Freight" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetVillefortColumbusV340FFreight() end },
	{ id = "Vehicles.GetVillefortCortesV5000ValorPink", name = "Villefort - Cortes V5000 Valor (pink)" , parent = "Vehicles" , description = "Add the vehicle Villefort - Cortes V5000 Valor (pink)" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetVillefortCortesV5000ValorPink() end },
	{ id = "Vehicles.GetVillefortCortesDelaminNo21", name = "Villefort - Cortes Delamain No.21" , parent = "Vehicles" , description = "Add the vehicle Villefort - Cortes Delamain No.21" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetVillefortCortesDelaminNo21() end },
	{ id = "Vehicles.GetChevalierEmperor620Ragnar", name = "Chevalier - Emperor 620 Ragnar" , parent = "Vehicles" , description = "Add the vehicle Chevalier - Emperor 620 Ragnar" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetChevalierEmperor620Ragnar() end },
	{ id = "Vehicles.GetChevalierThrax338Jefferson", name = "Chevalier - Thrax 338 Jefferson" , parent = "Vehicles" , description = "Add the vehicle Chevalier - Thrax 338 Jefferson" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetChevalierThrax338Jefferson() end },
	{ id = "Vehicles.GetBrennanApollo", name = "Brennan - Apollo" , parent = "Vehicles" , description = "Add the vehicle Brennan - Apollo" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetBrennanApollo() end },
	{ id = "Vehicles.GetBrennanApolloScorpion", name = "Brennan - Apollo 'Scorpion'" , parent = "Vehicles" , description = "Add the vehicle Brennan - Apollo 'Scorpion'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetBrennanApolloScorpion() end },
	{ id = "Vehicles.GetJackiesArch", name = "Jackie's Arch" , parent = "Vehicles" , description = "Add the vehicle Jackie's Arch" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetJackiesArch() end },
	{ id = "Vehicles.GetJackiesTunedArch", name = "Jackie's Tuned Arch" , parent = "Vehicles" , description = "Add the vehicle Jackie's Tuned Arch" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetJackiesTunedArch() end },
	{ id = "Vehicles.GetArchNazare", name = "Arch - Nazaré" , parent = "Vehicles" , description = "Add the vehicle Arch - Nazaré" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetArchNazare() end },
	{ id = "Vehicles.GetArchNazareItsumade", name = "Arch - Nazaré 'Itsumade'" , parent = "Vehicles" , description = "Add the vehicle Arch - Nazaré 'Itsumade'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetArchNazareItsumade() end },
	{ id = "Vehicles.GetYaibaKusanagiMizuchi", name = "Yaiba - Kusanagi 'Mizuchi'" , parent = "Vehicles" , description = "Add the vehicle Yaiba - Kusanagi 'Mizuchi'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetYaibaKusanagiMizuchi() end },
	{ id = "Vehicles.GetYaibaKusanagiCT3X", name = "Yaiba - Kusanagi CT-3X" , parent = "Vehicles" , description = "Add the vehicle Yaiba - Kusanagi CT-3X" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetYaibaKusanagiCT3X() end },
	{ id = "Vehicles.GetPorsche911Johnny", name = "Porsche - 911 Turbo" , parent = "Vehicles" , description = "Add the vehicle Porsche - 911 Turbo" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetPorsche911Johnny() end },
	{ id = "Vehicles.GetArcherQuartzECT2R660", name = "Archer - Quartz EC-T2 R660" , parent = "Vehicles" , description = "Add the vehicle Archer - Quartz EC-T2 R660" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetArcherQuartzECT2R660() end },
	{ id = "Vehicles.GetMizutaniShionCoyote", name = "Mizutani - Shion 'Coyote'" , parent = "Vehicles" , description = "Add the vehicle Mizutani - Shion 'Coyote'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetMizutaniShionCoyote() end },
	{ id = "Vehicles.GetMizutaniShionCoyoteRed", name = "Mizutani - Shion 'Coyote' (Red)" , parent = "Vehicles" , description = "Add the vehicle Mizutani - Shion 'Coyote' (Red)" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetMizutaniShionCoyoteRed() end },
	{ id = "Vehicles.GetMizutaniShionMZ2", name = "Mizutani - Shion MZ2" , parent = "Vehicles" , description = "Add the vehicle Mizutani - Shion MZ2" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetMizutaniShionMZ2() end },
	{ id = "Vehicles.GetQuadraTurboR740", name = "Quadra - Turbo-R 740" , parent = "Vehicles" , description = "Add the vehicle Quadra - Turbo-R 740" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetQuadraTurboR740() end },
	{ id = "Vehicles.GetQuadraTurboRVTech", name = "Quadra - Turbo-R V-Tech" , parent = "Vehicles" , description = "Add the vehicle Quadra - Turbo-R V-Tech" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetQuadraTurboRVTech() end },
	{ id = "Vehicles.GetQuadraType66Cthulhu", name = "Quadra - Type-66 'Cthulhu'" , parent = "Vehicles" , description = "Add the vehicle Quadra - Type-66 'Cthulhu'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetQuadraType66Cthulhu() end },
	{ id = "Vehicles.GetQuadraType66Javelina", name = "Quadra - Type-66 'Javelina'" , parent = "Vehicles" , description = "Add the vehicle Quadra - Type-66 'Javelina'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetQuadraType66Javelina() end },
	{ id = "Vehicles.GetQuadraType66JenRowley", name = "Quadra - Type-66 'Jen Rowley'" , parent = "Vehicles" , description = "Add the vehicle Quadra - Type-66 'Jen Rowley'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetQuadraType66JenRowley() end },
	{ id = "Vehicles.GetQuadraType66Avenger", name = "Quadra - Type-66 Avenger" , parent = "Vehicles" , description = "Add the vehicle Quadra - Type-66 Avenger" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetQuadraType66Avenger() end },
	{ id = "Vehicles.GetRayfieldAerondightGuinevere", name = "Rayfield - Aerondight 'Guinevere'" , parent = "Vehicles" , description = "Add the vehicle Rayfield - Aerondight 'Guinevere'" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetRayfieldAerondightGuinevere() end },
	{ id = "Vehicles.GetRayfieldCaliburn", name = "Rayfield - Caliburn" , parent = "Vehicles" , description = "Add the vehicle Rayfield - Caliburn" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetRayfieldCaliburn() end },
	{ id = "Vehicles.GetRayfieldCaliburnBlack", name = "Rayfield - Caliburn (black)" , parent = "Vehicles" , description = "Add the vehicle Rayfield - Caliburn (black)" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetRayfieldCaliburnBlack() end },
	{ id = "Vehicles.GetHerreraOutlawGTS", name = "Herrera - Outlaw GTS" , parent = "Vehicles" , description = "Add the vehicle Herrera - Outlaw GTS" , type = "Button" , button_label = "Execute" , cmd = function() BD.Vehicles.GetHerreraOutlawGTS() end }
  }
}

return Protocols
